name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install root tools (noop if none)
        run: |
          if [ -f package.json ]; then npm ci; fi
      - name: Build web app
        run: |
          if [ -d apps/web ]; then cd apps/web && npm ci && npm run build; fi
      - name: Lint web app
        run: |
          if [ -d apps/web ]; then cd apps/web && npm run -s lint || true; fi
      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.11'
      - name: Install server deps
        run: |
          if [ -f server/requirements.txt ]; then python -m pip install -r server/requirements.txt; fi
      - name: Run server tests
        run: |
          if [ -d server/tests ]; then pytest -q; fi

